import { StyleSheet, Platform } from "react-native";

const colors = {
  primary: "#F4F1DE",
  secondary: "#3D405B",
  green: "#81B29A",
  red: "#E07A5F",
  yellow: "#F2CC8F",
};

const styles = StyleSheet.create({
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  smallText: {
    fontSize: 16,
    color: colors.secondary,
  },
  text: {
    fontSize: 24,
    color: colors.secondary,
  },
  container: {
    flex: 1,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: 100,
  },
  button: {
    backgroundColor: colors.secondary,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 5,
    marginVertical: 10,
    textAlign: "center",
    alignItems: "center",
    minWidth: "80%",
  },
  buttonLight: {
    backgroundColor: colors.primary,
    borderColor: colors.secondary,
    borderWidth: 3,
  },
  buttonText: {
    color: colors.primary,
    fontSize: 30,
  },
  buttonTextLight: {
    color: colors.secondary,
  },
  input: {
    backgroundColor: colors.primary,
    color: colors.secondary,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 5,
    marginVertical: 10,
    textAlign: "center",
    alignItems: "center",
    minWidth: "80%",
    borderColor: colors.secondary,
    borderWidth: 2,
    fontSize: 30,
    textAlign: "center",
    fontWeight: "bold",
  },
  caption: {
    color: colors.secondary,
    fontSize: 20,
    textDecorationColor: colors.secondary,
    textDecorationLine: "underline",
  },
  modalScroll: {
    flex: 1,
  },
  modalInner: {
    padding: 20,
    paddingBottom: 0,
    justifyContent: "space-between",
    flexDirection: "column",
    flex: 1,
    height: "100%",
  },
  modalView: {
    margin: 10,
    backgroundColor: "white",
    borderRadius: 40,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.25,
    padding: 5,
    shadowRadius: 4,
    elevation: 5,
    backgroundColor: colors.primary,
    minHeight: 400,
    borderColor: colors.secondary,
    borderWidth: 2,
  },
  modalContent: {
    flex: 1,
    justifyContent: "flex-end",
    // alignItems: "center",
    marginHorizontal: "auto",
    marginTop: 122,
    minHeight: 100,
    width: "100%",
  },
  modalCloseButton: {
    minWidth: "100%",
    borderColor: colors.red,
    borderWidth: 2,
    borderRadius: 5,
    padding: 10,

    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 5,
    marginVertical: 10,
    textAlign: "center",
    alignItems: "center",
  },
  modalCloseButtonText: {
    color: colors.red,
    fontSize: 30,
  },
  footer: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  footerText: {
    color: colors.secondary,
    fontSize: 15,
  },
  deviceIdRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 10,
  },
  deviceIdLetter: {
    color: colors.secondary,
    fontSize: 30,
    borderWidth: 2,
    borderColor: colors.secondary,
    padding: 10,
    borderRadius: 5,
    fontWeight: "bold",
    flex: 1,
    textAlign: "center",
    marginHorizontal: 2,
  },
  deviceIdRegenerate: {
    color: colors.secondary,
    borderWidth: 2,
    borderColor: colors.secondary,
    padding: 10,
    borderRadius: 5,
    alignSelf: "flex-end",
  },
  deviceIdRegenerateText: {
    color: colors.secondary,
  },
  recievingHandlerBeaconContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 80,
    borderWidth: 2,
    borderRadius: 50,
    padding: 5,
    alignSelf: "flex-start",
    marginLeft: 10,
    paddingRight: 10,
  },
  recievingHandlerModalContainer: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  recievingHandlerModalTitle: {
    color: colors.secondary,
    fontSize: 30,
    marginBottom: 10,
    fontWeight: "bold",
    textAlign: "center",
  },
  recievingHandlerModalTable: {
    flexDirection: "column",
    borderTopWidth: 2,
    borderBottomWidth: 2,
    borderTopColor: colors.secondary,
    borderBottomColor: colors.secondary,
    borderLeftColor: colors.primary,
    borderRightColor: colors.primary,
  },
  recievingHandlerModalTableRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,

    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderTopColor: colors.secondary,
    borderBottomColor: colors.secondary,
    borderLeftColor: colors.primary,
    borderRightColor: colors.primary,
  },
});

export default styles;
export { colors };
